name: Check for new release

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    name: Check and tag new release
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-tags: true

      - name: Check and tag new release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          latest=$(gh api repos/woodruffw/zizmor/releases/latest --jq '.tag_name | ltrimstr("v")')
          if ! git ls-remote --exit-code origin "refs/tags/v$latest"; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag -a "v$latest" -m "v$latest"
            git push origin "v$latest"
          fi
